In [1]:
from pathlib import Path

from IPython.display import display

from searchlight.lightcurves import load
from searchlight.review_exports import (
    DEFAULT_METADATA_CACHE_PATH,
    DEFAULT_RESULT_CACHE_META_PATH,
    DEFAULT_RESULT_CACHE_PATH,
    enrich_results_with_metadata,
    load_lensing_results,
)
from searchlight.review_widgets import make_zooniverse_review_item
from searchlight.zooniverse_results import (
    DEFAULT_SUBJECT_METADATA_CACHE_PATH,
    DEFAULT_TASK_KEY,
    add_candidate_ids,
    annotate_most_likely_answers,
    load_zooniverse_results,
    select_zooniverse_answer_results,
)

In [2]:
RESULTS_PATH = Path('data/results/simulens1.0_tess_spoc')
RESULT_CACHE_PATH = DEFAULT_RESULT_CACHE_PATH
RESULT_CACHE_META_PATH = DEFAULT_RESULT_CACHE_META_PATH
RESULT_METADATA_CACHE_PATH = DEFAULT_METADATA_CACHE_PATH

# CSV exported from Zooniverse/aggregation, containing integer subject_id and data.most_likely.
ZOONIVERSE_RESULTS_CSV = Path('data/zooniverse/check_peaks_results.csv')
SUBJECT_METADATA_CACHE_PATH = DEFAULT_SUBJECT_METADATA_CACHE_PATH

# Set this explicitly if the CSV does not contain a workflow_id column.
WORKFLOW_ID = None
TASK_KEY = DEFAULT_TASK_KEY
MOST_LIKELY_ANSWER = 'Three or more peaks'
TOP_N = 100
MIN_CLASSIFICATIONS = 3
MIN_AGREEMENT = 0.7

In [3]:
# Zooniverse CSV loading, workflow answer lookup, subject metadata mapping,
# and review-card rendering live in searchlight modules so notebooks and
# exporters share the same implementation.

In [4]:
# Review widget implementation: searchlight.review_widgets.make_zooniverse_review_item

In [5]:
results = load_lensing_results(
    results_path=RESULTS_PATH,
    cache_path=RESULT_CACHE_PATH,
    cache_meta_path=RESULT_CACHE_META_PATH,
)
results = add_candidate_ids(results)
print(f'Loaded {len(results)} lensing model rows from {RESULTS_PATH}')

Loading cached results from data/results/simulens1.0_tess_spoc/top_resnet_results_cache.pkl
Loaded 2160368 lensing model rows from data/results/simulens1.0_tess_spoc

In [6]:
zooniverse = load_zooniverse_results(ZOONIVERSE_RESULTS_CSV)
zooniverse, workflow_id, answer_labels = annotate_most_likely_answers(
    zooniverse,
    workflow_id=WORKFLOW_ID,
    task_key=TASK_KEY,
)
zooniverse['most_likely_answer'].value_counts(dropna=False)

Workflow 31708 T0 answers: {0: 'None, it just contains noise or stellar variability', 1: 'One peak', 2: 'Two peaks', 3: 'Three or more peaks'}

most_likely_answer
One peak                                               34031
None, it just contains noise or stellar variability    20400
NaN                                                     8085
Two peaks                                               4049
Three or more peaks                                     2215
Name: count, dtype: int64

In [7]:
selected = select_zooniverse_answer_results(
    results,
    zooniverse,
    MOST_LIKELY_ANSWER,
    MIN_CLASSIFICATIONS, 
    MIN_AGREEMENT,
    subject_metadata_cache_path=SUBJECT_METADATA_CACHE_PATH,
)
review_results = selected.head(TOP_N).copy()
review_results[['subject_id', 'most_likely_answer', 'data.num_votes', 'data.agreement', 'candidate_id', 'path', 'lensing']].head()

Fetching Zooniverse subjects: 0subject [00:00, ?subject/s]

Selected 35 rows where most_likely_answer == 'Three or more peaks'
Mapped 35 selected subjects to paths

,subject_id,most_likely_answer,data.num_votes,data.agreement,candidate_id,path,lensing
0,119505647,Three or more peaks,3,1.00,9f741e5f-eaad-5f7c-ad8a-ab4321d4f1ef,https://mast.stsci.edu/api/v0.1/Download/file/...,5.102989
1,119512525,Three or more peaks,3,0.75,bac62b59-152d-5943-9beb-c91c617177a4,https://mast.stsci.edu/api/v0.1/Download/file/...,4.697097
2,119526852,Three or more peaks,3,1.00,1557a46c-24fc-5da0-8ed6-7ceda653d2ae,https://mast.stsci.edu/api/v0.1/Download/file/...,4.331447
3,119529212,Three or more peaks,3,1.00,68e067cc-702c-5bfc-bc5d-f5a70be2ce6b,https://mast.stsci.edu/api/v0.1/Download/file/...,4.280339
4,119530411,Three or more peaks,3,1.00,e5aefd8a-62c3-52ba-b453-fdc67881cb98,https://mast.stsci.edu/api/v0.1/Download/file/...,4.250017

In [8]:
review_export = enrich_results_with_metadata(
    review_results,
    cache_path=RESULT_METADATA_CACHE_PATH,
)
review_export[[
    'subject_id',
    'most_likely_answer',
    'data.num_votes',
    'data.agreement',
    'path',
    'lensing',
    'tic',
    'sector',
    'simbad_url',
]].head()

,subject_id,most_likely_answer,data.num_votes,data.agreement,path,lensing,tic,sector,simbad_url
0,119505647,Three or more peaks,3,1.00,https://mast.stsci.edu/api/v0.1/Download/file/...,5.102989,395182982,38,https://simbad.cds.unistra.fr/simbad/sim-coo?C...
1,119512525,Three or more peaks,3,0.75,https://mast.stsci.edu/api/v0.1/Download/file/...,4.697097,84369799,55,https://simbad.cds.unistra.fr/simbad/sim-coo?C...
2,119526852,Three or more peaks,3,1.00,https://mast.stsci.edu/api/v0.1/Download/file/...,4.331447,432928699,36,https://simbad.cds.unistra.fr/simbad/sim-coo?C...
3,119529212,Three or more peaks,3,1.00,https://mast.stsci.edu/api/v0.1/Download/file/...,4.280339,306107053,39,https://simbad.cds.unistra.fr/simbad/sim-coo?C...
4,119530411,Three or more peaks,3,1.00,https://mast.stsci.edu/api/v0.1/Download/file/...,4.250017,138019165,58,https://simbad.cds.unistra.fr/simbad/sim-coo?C...

In [9]:
for row in review_results.to_dict('records'):
    lc = load(row['path'])
    display(make_zooniverse_review_item(row, lc))

0% (12/3705) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:0% (12/3705) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000395182982-s0038_tess_v1_lc.f…

0% (10/3781) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:0% (10/3781) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000084369799-s0055_tess_v1_lc.f…

0% (10/3477) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:0% (10/3477) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000432928699-s0036_tess_v1_lc.f…

0% (14/3879) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:0% (14/3879) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000306107053-s0039_tess_v1_lc.f…

0% (12/11704) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:0% (12/11704) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000138019165-s0058_tess_v1_lc.f…

0% (10/3927) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:0% (10/3927) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000358699700-s0040_tess_v1_lc.f…

0% (10/3477) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:0% (10/3477) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000444230722-s0036_tess_v1_lc.f…

16% (538/3353) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:16% (538/3353) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000309255314-s0035_tess_v1_lc.f…

1% (80/11356) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:1% (80/11356) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000359269899-s0064_tess_v1_lc.f…

0% (11/3354) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:0% (11/3354) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000388434990-s0052_tess_v1_lc.f…

1% (80/11356) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:1% (80/11356) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000261220610-s0064_tess_v1_lc.f…

7% (257/3635) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:7% (257/3635) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000137796568-s0029_tess_v1_lc.f…

0% (11/3600) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:0% (11/3600) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000300814832-s0032_tess_v1_lc.f…

1% (60/10713) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:1% (60/10713) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000458621085-s0061_tess_v1_lc.f…

0% (10/3495) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:0% (10/3495) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000098045798-s0033_tess_v1_lc.f…

0% (14/3879) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:0% (14/3879) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000220978100-s0039_tess_v1_lc.f…

0% (40/10730) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:0% (40/10730) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000405303645-s0070_tess_v1_lc.f…

2% (59/3450) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:2% (59/3450) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000458619256-s0045_tess_v1_lc.f…

0% (19/10730) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:0% (19/10730) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000097367773-s0070_tess_v1_lc.f…

1% (17/3278) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:1% (17/3278) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000014158303-s0044_tess_v1_lc.f…

0% (43/11076) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:0% (43/11076) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000233291884-s0081_tess_v1_lc.f…

1% (7/1093) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:1% (7/1093) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000080542255-s0007_tess_v1_lc.f…

2% (232/10730) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:2% (232/10730) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000344625990-s0070_tess_v1_lc.f…

14% (1618/11719) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:14% (1618/11719) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000218905635-s0067_tess_v1_lc.f…

0% (10/3927) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:0% (10/3927) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000137408591-s0040_tess_v1_lc.f…

3% (89/3278) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:3% (89/3278) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000387442273-s0044_tess_v1_lc.f…

0% (15/3489) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:0% (15/3489) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000271386165-s0034_tess_v1_lc.f…

0% (12/3466) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:0% (12/3466) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000236848644-s0053_tess_v1_lc.f…

0% (2/1148) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:0% (2/1148) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000383754985-s0026_tess_v1_lc.f…

0% (43/11076) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:0% (43/11076) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000137408591-s0081_tess_v1_lc.f…

0% (26/10837) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:0% (26/10837) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000134642006-s0062_tess_v1_lc.f…

1% (7/1093) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:1% (7/1093) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000355408846-s0007_tess_v1_lc.f…

0% (10/3781) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:0% (10/3781) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000087180382-s0055_tess_v1_lc.f…

0% (16/3477) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:0% (16/3477) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000220440490-s0037_tess_v1_lc.f…

0% (10/3781) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:0% (10/3781) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000279400254-s0055_tess_v1_lc.f…