In [1]:
from pathlib import Path

from IPython.display import display

from searchlight.lightcurves import load
from searchlight.review_exports import (
    DEFAULT_METADATA_CACHE_PATH,
    DEFAULT_RESULT_CACHE_META_PATH,
    DEFAULT_RESULT_CACHE_PATH,
    enrich_results_with_metadata,
    load_lensing_results,
)
from searchlight.review_widgets import make_zooniverse_review_item
from searchlight.zooniverse_results import (
    DEFAULT_SUBJECT_METADATA_CACHE_PATH,
    DEFAULT_TASK_KEY,
    add_candidate_ids,
    annotate_most_likely_answers,
    load_zooniverse_results,
    select_zooniverse_answer_results,
)

In [2]:
RESULTS_PATH = Path('data/results/simulens1.0_tess_spoc')
RESULT_CACHE_PATH = DEFAULT_RESULT_CACHE_PATH
RESULT_CACHE_META_PATH = DEFAULT_RESULT_CACHE_META_PATH
RESULT_METADATA_CACHE_PATH = DEFAULT_METADATA_CACHE_PATH

# CSV exported from Zooniverse/aggregation, containing integer subject_id and data.most_likely.
ZOONIVERSE_RESULTS_CSV = Path('data/zooniverse/check_peaks_results.csv')
SUBJECT_METADATA_CACHE_PATH = DEFAULT_SUBJECT_METADATA_CACHE_PATH

# Set this explicitly if the CSV does not contain a workflow_id column.
WORKFLOW_ID = None
TASK_KEY = DEFAULT_TASK_KEY
MOST_LIKELY_ANSWER = 'Three or more peaks'
TOP_N = 100

In [3]:
# Zooniverse CSV loading, workflow answer lookup, subject metadata mapping,
# and review-card rendering live in searchlight modules so notebooks and
# exporters share the same implementation.

In [4]:
# Review widget implementation: searchlight.review_widgets.make_zooniverse_review_item

In [5]:
results = load_lensing_results(
    results_path=RESULTS_PATH,
    cache_path=RESULT_CACHE_PATH,
    cache_meta_path=RESULT_CACHE_META_PATH,
)
results = add_candidate_ids(results)
print(f'Loaded {len(results)} lensing model rows from {RESULTS_PATH}')

Loading cached results from data/results/simulens1.0_tess_spoc/top_resnet_results_cache.pkl
Loaded 2160368 lensing model rows from data/results/simulens1.0_tess_spoc

In [6]:
zooniverse = load_zooniverse_results(ZOONIVERSE_RESULTS_CSV)
zooniverse, workflow_id, answer_labels = annotate_most_likely_answers(
    zooniverse,
    workflow_id=WORKFLOW_ID,
    task_key=TASK_KEY,
)
zooniverse['most_likely_answer'].value_counts(dropna=False)

Workflow 31708 T0 answers: {0: 'None, it just contains noise or stellar variability', 1: 'One peak', 2: 'Two peaks', 3: 'Three or more peaks'}

most_likely_answer
NaN                                                    2300
One peak                                               1751
None, it just contains noise or stellar variability    1210
Two peaks                                               182
Three or more peaks                                      53
Name: count, dtype: int64

In [7]:
selected = select_zooniverse_answer_results(
    results,
    zooniverse,
    MOST_LIKELY_ANSWER,
    subject_metadata_cache_path=SUBJECT_METADATA_CACHE_PATH,
)
review_results = selected.head(TOP_N).copy()
review_results[['subject_id', 'most_likely_answer', 'data.num_votes', 'data.agreement', 'candidate_id', 'path', 'lensing']].head()

Fetching Zooniverse subjects: 0subject [00:00, ?subject/s]

Selected 53 rows where most_likely_answer == 'Three or more peaks'
Mapped 53 selected subjects to paths

,subject_id,most_likely_answer,data.num_votes,data.agreement,candidate_id,path,lensing
0,119507226,Three or more peaks,1,1.0,d3ca8770-9e94-5781-9704-e9a05416199f,https://mast.stsci.edu/api/v0.1/Download/file/...,4.978697
1,119513747,Three or more peaks,1,1.0,b7411392-a6d9-53eb-8ae1-6301a28f720d,https://mast.stsci.edu/api/v0.1/Download/file/...,4.645565
2,119513830,Three or more peaks,1,1.0,28f25bb4-7d34-599f-ba99-e7178f91bdb7,https://mast.stsci.edu/api/v0.1/Download/file/...,4.642256
3,119516012,Three or more peaks,1,0.5,d0b8b7d1-f7c5-5947-b3e8-e1ad74da3547,https://mast.stsci.edu/api/v0.1/Download/file/...,4.558604
4,119522742,Three or more peaks,1,1.0,f5746f8e-7168-5b4c-89c4-1c24b6ba04a2,https://mast.stsci.edu/api/v0.1/Download/file/...,4.394792

In [8]:
review_export = enrich_results_with_metadata(
    review_results,
    cache_path=RESULT_METADATA_CACHE_PATH,
)
review_export[[
    'subject_id',
    'most_likely_answer',
    'data.num_votes',
    'data.agreement',
    'path',
    'lensing',
    'tic',
    'sector',
    'simbad_url',
]].head()

,subject_id,most_likely_answer,data.num_votes,data.agreement,path,lensing,tic,sector,simbad_url
0,119507226,Three or more peaks,1,1.0,https://mast.stsci.edu/api/v0.1/Download/file/...,4.978697,437060307,46,https://simbad.cds.unistra.fr/simbad/sim-coo?C...
1,119513747,Three or more peaks,1,1.0,https://mast.stsci.edu/api/v0.1/Download/file/...,4.645565,284613078,33,https://simbad.cds.unistra.fr/simbad/sim-coo?C...
2,119513830,Three or more peaks,1,1.0,https://mast.stsci.edu/api/v0.1/Download/file/...,4.642256,63664338,33,https://simbad.cds.unistra.fr/simbad/sim-coo?C...
3,119516012,Three or more peaks,1,0.5,https://mast.stsci.edu/api/v0.1/Download/file/...,4.558604,287425173,33,https://simbad.cds.unistra.fr/simbad/sim-coo?C...
4,119522742,Three or more peaks,1,1.0,https://mast.stsci.edu/api/v0.1/Download/file/...,4.394792,15853326,70,https://simbad.cds.unistra.fr/simbad/sim-coo?C...

In [9]:
for row in review_results.to_dict('records'):
    lc = load(row['path'])
    display(make_zooniverse_review_item(row, lc))

4% (145/3707) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:4% (145/3707) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000437060307-s0046_tess_v1_lc.f…

0% (10/3495) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:0% (10/3495) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000284613078-s0033_tess_v1_lc.f…

0% (10/3495) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:0% (10/3495) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000063664338-s0033_tess_v1_lc.f…

0% (10/3495) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:0% (10/3495) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000287425173-s0033_tess_v1_lc.f…

1% (142/10730) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:1% (142/10730) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000015853326-s0070_tess_v1_lc.f…

0% (51/10932) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:0% (51/10932) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000097431044-s0071_tess_v1_lc.f…

4% (450/11356) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:4% (450/11356) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000287047988-s0064_tess_v1_lc.f…

7% (247/3783) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:7% (247/3783) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000262821577-s0030_tess_v1_lc.f…

0% (10/3477) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:0% (10/3477) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000432928699-s0036_tess_v1_lc.f…

0% (12/11704) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:0% (12/11704) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000301916416-s0058_tess_v1_lc.f…

0% (14/3879) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:0% (14/3879) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000079067840-s0039_tess_v1_lc.f…

0% (12/11704) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:0% (12/11704) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000082393678-s0058_tess_v1_lc.f…

0% (51/10932) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:0% (51/10932) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000404713668-s0071_tess_v1_lc.f…

1% (15/1282) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:1% (15/1282) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000404850274-s0001_tess_v1_lc.f…

2% (59/3450) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:2% (59/3450) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000014439051-s0045_tess_v1_lc.f…

0% (26/10898) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:0% (26/10898) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000365410955-s0082_tess_v1_lc.f…

0% (2/1148) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:0% (2/1148) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000233689243-s0026_tess_v1_lc.f…

13% (1367/10932) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:13% (1367/10932) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000408836986-s0071_tess_v1_lc.f…

0% (16/3477) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:0% (16/3477) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000464744680-s0037_tess_v1_lc.f…

0% (12/3466) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:0% (12/3466) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000289798419-s0053_tess_v1_lc.f…

1% (12/993) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:1% (12/993) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000049084752-s0006_tess_v1_lc.f…

2% (159/8642) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:2% (159/8642) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000068539746-s0060_tess_v1_lc.f…

0% (14/3879) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:0% (14/3879) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000222228679-s0039_tess_v1_lc.f…

0% (14/10730) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:0% (14/10730) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000406409728-s0070_tess_v1_lc.f…

1% (7/1093) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:1% (7/1093) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000148588723-s0007_tess_v1_lc.f…

5% (195/3707) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:5% (195/3707) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000156582898-s0046_tess_v1_lc.f…

0% (15/3489) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:0% (15/3489) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000271386165-s0034_tess_v1_lc.f…

0% (17/3489) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:0% (17/3489) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000459056563-s0034_tess_v1_lc.f…

0% (5/1155) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:0% (5/1155) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000366975598-s0019_tess_v1_lc.f…

17% (621/3623) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:17% (621/3623) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000257787629-s0050_tess_v1_lc.f…

4% (456/10932) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:4% (456/10932) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000385554728-s0071_tess_v1_lc.f…

1% (11/968) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:1% (11/968) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000022595494-s0008_tess_v1_lc.f…

2% (79/3450) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:2% (79/3450) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000087957155-s0045_tess_v1_lc.f…

1% (21/3278) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:1% (21/3278) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000113801550-s0044_tess_v1_lc.f…

0% (10/3495) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:0% (10/3495) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000299586770-s0033_tess_v1_lc.f…

0% (5/1155) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:0% (5/1155) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000353961964-s0019_tess_v1_lc.f…

1% (80/11356) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:1% (80/11356) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000130728901-s0064_tess_v1_lc.f…

0% (26/10837) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:0% (26/10837) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000308608470-s0062_tess_v1_lc.f…

2% (16/968) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:2% (16/968) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000183260266-s0008_tess_v1_lc.f…

7% (718/10702) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:7% (718/10702) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000240057767-s0072_tess_v1_lc.f…

0% (10/3495) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:0% (10/3495) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000148588723-s0033_tess_v1_lc.f…

4% (487/11076) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:4% (487/11076) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000402537447-s0081_tess_v1_lc.f…

4% (145/3707) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:4% (145/3707) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000437026879-s0046_tess_v1_lc.f…

1% (7/1093) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:1% (7/1093) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000292843871-s0007_tess_v1_lc.f…

0% (5/1155) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:0% (5/1155) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000187424060-s0019_tess_v1_lc.f…

16% (549/3534) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:16% (549/3534) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000248050968-s0042_tess_v1_lc.f…

3% (127/3707) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:3% (127/3707) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000320195914-s0046_tess_v1_lc.f…

0% (16/11694) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:0% (16/11694) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000195449500-s0075_tess_v1_lc.f…

4% (461/10358) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:4% (461/10358) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000367523191-s0073_tess_v1_lc.f…

0% (9/11775) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:0% (9/11775) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000423326676-s0056_tess_v1_lc.f…

0% (11/3354) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:0% (11/3354) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000287151928-s0052_tess_v1_lc.f…

1% (17/3278) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:1% (17/3278) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000035155735-s0044_tess_v1_lc.f…

2% (248/11190) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).
INFO:lightkurve.utils:2% (248/11190) of the cadences will be ignored due to the quality mask (quality_bitmask=17087).

VBox(children=(HBox(children=(HTML(value='<strong>hlsp_tess-spoc_tess_phot_0000000138999193-s0063_tess_v1_lc.f…